
version: "3.5"

networks:
  b0:
    driver: bridge

services:
  ssdd:
    build:
      context: ./
      dockerfile: ./u20-dockerfile
    image: u20
    volumes:
      - type: bind
        source: .
        target: /work
    networks:
      - b0

